giosc1 OSCinit 9999	

gamain init 0	

gasrc1, gasrc2, gasrc3, gasrc4 init 0

gimfp init 0

giorder init 1

gklisxSmooth, gklisySmooth, gkliszSmooth, gklisdirSmooth init 0

gksrcOnTrig1, gksrcOnTrig2, gksrcOnTrig3, gksrcOnTrig4, gksrcTrigAny, gksrcOn1, gksrcOn2, gksrcOn3, gksrcOn4, gkrevtrig gktrig, gkend, gktrigSrc1, gktrigSrc2, gktrigSrc3, gktrigSrc4 init 0

gklisx, gklisy, gklisz, gklisdir init 0

gkroomx, gkroomy, gkroomz, gklowtime, gkhightime, gkwallhigh, gkwalllow, gkwallgain1, gkwallgain2, gkwallgain3, gkfloorhigh, gkfloorlow, gkfloorgain1, gkfloorgain2, gkfloorgain3, gkceilinghigh, gkceilinglow, gkceilinggain1, gkceilinggain2, gkceilinggain3 init 0
	
gkname1, gkname2, gkname3, gkname4 init 0
	
gkloop1, gkloop2, gkloop3, gkloop4 init 0
